version: 2
updates:
  # Maintain dependencies for Composer
  - package-ecosystem: 'composer'
    directory: '/'
    target-branch: "develop"
    schedule:
      interval: 'daily'
  # Maintain dependencies for yarn
  - package-ecosystem: 'yarn'
    directory: '/'
    target-branch: "develop"
    schedule:
      interval: 'daily'

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "daily"
